apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "worker-service.fullname" . }}
  labels:
    {{- include "worker-service.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "worker-service.selectorLabels" . | nindent 6 }}
