image:
  repository: us-central1-docker.pkg.dev/boba-dev-000000/boba-containers-dev/worker
serviceAccount:
  gcpServiceAccount: boba-worker-dev@boba-dev-000000.iam.gserviceaccount.com
config:
  NODE_ENV: development
