image:
  repository: us-central1-docker.pkg.dev/boba-dev-000000/boba-containers-dev/api
serviceAccount:
  gcpServiceAccount: boba-api-gw-dev@boba-dev-000000.iam.gserviceaccount.com
config:
  NODE_ENV: development
